import { Product, Category, BlogPost } from '@/types';

export const categories: Category[] = [
  { id: '1', name: 'Electronics', icon: '💻', count: 124, image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400' },
  { id: '2', name: 'Fashion', icon: '👗', count: 89, image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=400' },
  { id: '3', name: 'Home & Garden', icon: '🏠', count: 67, image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400' },
  { id: '4', name: 'Sports', icon: '⚽', count: 45, image: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=400' },
  { id: '5', name: 'Books', icon: '📚', count: 203, image: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400' },
  { id: '6', name: 'Beauty', icon: '💄', count: 78, image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400' },
  { id: '7', name: 'Toys', icon: '🧸', count: 56, image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400' },
  { id: '8', name: 'Automotive', icon: '🚗', count: 34, image: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=400' },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Premium Wireless Headphones',
    description: 'Experience crystal-clear audio with our premium wireless headphones. Features active noise cancellation, 30-hour battery life, and premium leather ear cushions for maximum comfort.',
    price: 89.99,
    originalPrice: 129.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600',
      'https://images.unsplash.com/photo-1524678606370-a47ad25cb82a?w=600',
    ],
    rating: 4.8,
    reviewCount: 234,
    stock: 45,
    brand: 'SoundMaster',
    tags: ['wireless', 'noise-cancelling', 'premium'],
    featured: true,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Smart Watch Pro X',
    description: 'Track your fitness goals with precision. Features heart rate monitoring, GPS tracking, sleep analysis, and 7-day battery life. Water resistant up to 50 meters.',
    price: 199.99,
    originalPrice: 249.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600',
    rating: 4.6,
    reviewCount: 189,
    stock: 23,
    brand: 'TechFit',
    tags: ['smartwatch', 'fitness', 'gps'],
    featured: true,
    createdAt: '2024-01-10',
  },
  {
    id: '3',
    name: 'Minimalist Leather Wallet',
    description: 'Slim, stylish and functional. This genuine leather wallet holds up to 8 cards and cash without adding bulk to your pocket. RFID blocking technology keeps your cards safe.',
    price: 34.99,
    originalPrice: 49.99,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=600',
    rating: 4.7,
    reviewCount: 312,
    stock: 78,
    brand: 'LeatherCraft',
    tags: ['wallet', 'leather', 'slim'],
    featured: false,
    createdAt: '2024-02-01',
  },
  {
    id: '4',
    name: 'Yoga Mat Premium',
    description: 'Non-slip, eco-friendly yoga mat perfect for all types of yoga and exercise. Extra thick 6mm cushioning provides joint support. Includes carrying strap.',
    price: 45.99,
    category: 'Sports',
    image: 'https://images.unsplash.com/photo-1601925228984-f6b2c1e3c11c?w=600',
    rating: 4.5,
    reviewCount: 156,
    stock: 92,
    brand: 'ZenFit',
    tags: ['yoga', 'fitness', 'eco-friendly'],
    featured: false,
    createdAt: '2024-01-25',
  },
  {
    id: '5',
    name: 'Ceramic Coffee Mug Set',
    description: 'Handcrafted ceramic mugs with a beautiful matte finish. Set of 4, each holding 12oz. Dishwasher and microwave safe. Perfect for morning coffee or evening tea.',
    price: 28.99,
    originalPrice: 39.99,
    category: 'Home & Garden',
    image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600',
    rating: 4.9,
    reviewCount: 421,
    stock: 134,
    brand: 'CeraHome',
    tags: ['kitchen', 'ceramic', 'mug'],
    featured: true,
    createdAt: '2024-02-10',
  },
  {
    id: '6',
    name: 'Portable Bluetooth Speaker',
    description: '360° surround sound with deep bass. Waterproof IPX7 rating, 24-hour playtime, and built-in microphone for hands-free calls. Perfect for outdoor adventures.',
    price: 59.99,
    originalPrice: 79.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600',
    rating: 4.4,
    reviewCount: 278,
    stock: 56,
    brand: 'SoundMaster',
    tags: ['speaker', 'bluetooth', 'waterproof'],
    featured: false,
    createdAt: '2024-01-20',
  },
  {
    id: '7',
    name: 'Skincare Essential Kit',
    description: 'Complete skincare routine in one kit. Includes gentle cleanser, vitamin C serum, hyaluronic acid moisturizer, and SPF 50 sunscreen. Suitable for all skin types.',
    price: 79.99,
    originalPrice: 109.99,
    category: 'Beauty',
    image: 'https://images.unsplash.com/photo-1570194065650-d99fb4bedf0a?w=600',
    rating: 4.7,
    reviewCount: 198,
    stock: 45,
    brand: 'GlowSkin',
    tags: ['skincare', 'beauty', 'kit'],
    featured: true,
    createdAt: '2024-02-05',
  },
  {
    id: '8',
    name: 'Running Shoes Pro',
    description: 'Lightweight yet durable running shoes with advanced cushioning technology. Breathable mesh upper keeps feet cool. Available in multiple colors and sizes.',
    price: 119.99,
    originalPrice: 149.99,
    category: 'Sports',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600',
    rating: 4.6,
    reviewCount: 345,
    stock: 67,
    brand: 'SpeedRun',
    tags: ['shoes', 'running', 'sports'],
    featured: false,
    createdAt: '2024-01-30',
  },
  {
    id: '9',
    name: 'Mechanical Keyboard RGB',
    description: 'Tactile mechanical switches with satisfying click. Full RGB backlight with 16 million colors. Compact TKL design saves desk space. PBT keycaps for durability.',
    price: 89.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600',
    rating: 4.8,
    reviewCount: 267,
    stock: 34,
    brand: 'KeyMaster',
    tags: ['keyboard', 'mechanical', 'rgb'],
    featured: false,
    createdAt: '2024-02-15',
  },
  {
    id: '10',
    name: 'Scented Candle Collection',
    description: 'Luxury soy wax candles with essential oil blends. Set of 3 with lavender, vanilla, and eucalyptus scents. 45-hour burn time each. Beautifully packaged for gifting.',
    price: 39.99,
    category: 'Home & Garden',
    image: 'https://images.unsplash.com/photo-1602607034069-1d6b3b0e1f0e?w=600',
    rating: 4.9,
    reviewCount: 512,
    stock: 89,
    brand: 'AromaLux',
    tags: ['candles', 'home', 'gift'],
    featured: false,
    createdAt: '2024-02-08',
  },
  {
    id: '11',
    name: 'LEGO Architecture Set',
    description: 'Build iconic world landmarks with this detailed LEGO architecture set. Includes 1200+ pieces and step-by-step instructions. Perfect for ages 12+ and LEGO enthusiasts.',
    price: 69.99,
    originalPrice: 89.99,
    category: 'Toys',
    image: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600',
    rating: 4.8,
    reviewCount: 189,
    stock: 23,
    brand: 'BrickWorld',
    tags: ['lego', 'toys', 'architecture'],
    featured: false,
    createdAt: '2024-01-18',
  },
  {
    id: '12',
    name: 'Car Phone Mount Pro',
    description: 'Universal magnetic car mount with strong magnet and 360° rotation. Compatible with all smartphones. Easy one-hand operation. No blocking air vents.',
    price: 19.99,
    originalPrice: 29.99,
    category: 'Automotive',
    image: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=600',
    rating: 4.5,
    reviewCount: 634,
    stock: 156,
    brand: 'DriveMount',
    tags: ['car', 'phone mount', 'magnetic'],
    featured: false,
    createdAt: '2024-01-12',
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: '1',
    title: '10 Must-Have Tech Gadgets for 2024',
    excerpt: 'Explore the latest and greatest tech gadgets that are transforming our daily lives this year.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=600',
    author: 'Alex Johnson',
    category: 'Technology',
    date: 'March 15, 2024',
    readTime: '5 min read',
  },
  {
    id: '2',
    title: 'Sustainable Fashion: Shop Smart, Live Green',
    excerpt: 'How to build a sustainable wardrobe without breaking the bank or the planet.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=600',
    author: 'Emma Williams',
    category: 'Fashion',
    date: 'March 10, 2024',
    readTime: '7 min read',
  },
  {
    id: '3',
    title: 'The Ultimate Home Workout Setup Guide',
    excerpt: 'Transform your living space into a professional-grade home gym with the right equipment.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1534258936925-c58bed479fcb?w=600',
    author: 'Mark Davis',
    category: 'Fitness',
    date: 'March 5, 2024',
    readTime: '6 min read',
  },
  {
    id: '4',
    title: 'Skincare Routine for Beginners',
    excerpt: 'Start your skincare journey with these essential steps and product recommendations.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600',
    author: 'Sarah Chen',
    category: 'Beauty',
    date: 'Feb 28, 2024',
    readTime: '4 min read',
  },
  {
    id: '5',
    title: 'Gift Guide: Best Products Under $50',
    excerpt: 'Find the perfect gift for everyone on your list without overspending.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=600',
    author: 'Lisa Park',
    category: 'Shopping',
    date: 'Feb 20, 2024',
    readTime: '8 min read',
  },
  {
    id: '6',
    title: 'How to Choose the Right Running Shoes',
    excerpt: 'Expert advice on selecting running shoes based on your gait, terrain, and fitness goals.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=600',
    author: 'Tom Wilson',
    category: 'Sports',
    date: 'Feb 15, 2024',
    readTime: '5 min read',
  },
];

export const stats = [
  { label: 'Happy Customers', value: '50K+', icon: '😊' },
  { label: 'Products Available', value: '10K+', icon: '📦' },
  { label: 'Countries Served', value: '45+', icon: '🌍' },
  { label: 'Years of Trust', value: '8+', icon: '⭐' },
];

export const testimonials = [
  {
    id: '1',
    name: 'Sarah Johnson',
    role: 'Regular Customer',
    avatar: 'https://i.pravatar.cc/100?img=1',
    rating: 5,
    comment: 'ShopAI has completely transformed my online shopping experience. The AI chatbot helped me find exactly what I needed within minutes!',
  },
  {
    id: '2',
    name: 'Michael Chen',
    role: 'Tech Enthusiast',
    avatar: 'https://i.pravatar.cc/100?img=2',
    rating: 5,
    comment: 'Amazing product quality and lightning-fast delivery. The product recommendations are spot on every single time.',
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    role: 'Fashion Blogger',
    avatar: 'https://i.pravatar.cc/100?img=3',
    rating: 4,
    comment: 'Great selection of fashion items at competitive prices. Customer service is top-notch. Highly recommend!',
  },
  {
    id: '4',
    name: 'David Kim',
    role: 'Fitness Coach',
    avatar: 'https://i.pravatar.cc/100?img=4',
    rating: 5,
    comment: 'The sports equipment selection is incredible. Fast shipping and the items are exactly as described. Will keep coming back!',
  },
];
